% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Estratégias Inferenciais}
\author{Edgar Luiz de Lima}
\date{11/03/2022}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Estratégias Inferenciais},
  pdfauthor={Edgar Luiz de Lima},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

\hypertarget{dados}{%
\section{Dados}\label{dados}}

O conjunto de dados que iremos utilizar foi retirado de um conjuto de
dados muito maior de Mazerolle \& Desrochers (2005).

Ele apresenta as seguintes variáveis:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Shade: variável binária indicando se o indivíduo foi coletado na
  sombra(1= sim, 0= não).
\item
  Cloud: cobertura de núvem expressa em porcentagem.
\item
  Airtemp: temperatura do ar em graus celcius.
\item
  Mass\_lost: perda de massa corporal em gramas.
\item
  Aqui iremos definir o diretório, carregar os pacotes e o banco de
  dados.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(MuMIn)}
\FunctionTok{library}\NormalTok{(openxlsx)}
\NormalTok{dados}\OtherTok{\textless{}{-}} \FunctionTok{read.xlsx}\NormalTok{(}\StringTok{"Dados.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

1.2. Vamos visualizar as 10 primeiras linhas do conjunto de dados.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(dados, }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Shade Cloud Airtemp Mass_lost
## 1      0    20      31       8.3
## 2      0    20      31       3.6
## 3      0    20      31       4.7
## 4      0     5      22       7.0
## 5      0     5      22       7.7
## 6      0     5      22       1.6
## 7      0    10      25       6.4
## 8      0    10      25       5.9
## 9      0    10      25       2.8
## 10     0     5      23       3.4
\end{verbatim}

1.3. Agora precisamos checar como o formato em que o R leu os dados,
para saber se os dados estão no formato correto.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(dados)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    121 obs. of  4 variables:
##  $ Shade    : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Cloud    : num  20 20 20 5 5 5 10 10 10 5 ...
##  $ Airtemp  : num  31 31 31 22 22 22 25 25 25 23 ...
##  $ Mass_lost: num  8.3 3.6 4.7 7 7.7 1.6 6.4 5.9 2.8 3.4 ...
\end{verbatim}

Podemos ver que a variável Shade está sendo interpretada como variável
numérica, mas na verdade ela deve ser interpretatada como uma variável
categórica.

Então vamos converter ela em fator, e depois checar se ela realmente foi
interpretada como fator.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dados}\SpecialCharTok{$}\NormalTok{Shade}\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(dados}\SpecialCharTok{$}\NormalTok{Shade)}
\FunctionTok{str}\NormalTok{(dados)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    121 obs. of  4 variables:
##  $ Shade    : Factor w/ 2 levels "0","1": 1 1 1 1 1 1 1 1 1 1 ...
##  $ Cloud    : num  20 20 20 5 5 5 10 10 10 5 ...
##  $ Airtemp  : num  31 31 31 22 22 22 25 25 25 23 ...
##  $ Mass_lost: num  8.3 3.6 4.7 7 7.7 1.6 6.4 5.9 2.8 3.4 ...
\end{verbatim}

Agora o R está interpretando ela como fator, e está nos dizendo que ela
possui os níveis 0 e 1, que significam não estar na sombra e estar na
sombra respectavamente.

\hypertarget{testando-as-nossas-hipuxf3teses}{%
\section{Testando as nossas
hipóteses}\label{testando-as-nossas-hipuxf3teses}}

Antes de testar as nossas hipoteses precisamos entender primeiro como
descrevemos o nosso modelo estatístico no R. Para isso utilizamos o a
função lm() que significar linear model, e especificamos o noss modelo
da seguinte maneira.

\begin{verbatim}
           lm(y~x, data) 
\end{verbatim}

onde: 1. y= é a variável resposta, nesse caso Mass\_lost; 2. x= é a
variável preditora, no nosso caso teremos três variáveis preditoras; 3.
data= é o conjunto de dados que as minhas variáveis fazem parte. 4.
til(\textasciitilde)= significa em função de, ou seha, minha variável
resposta em função das variáveis preditoras.

\hypertarget{teste-de-significancia-da-hipuxf3tese-nula-nhst}{%
\subsection{1. Teste de significancia da hipótese nula
(NHST)}\label{teste-de-significancia-da-hipuxf3tese-nula-nhst}}

1.1 Primeiramente, temos que especificar o nosso modelo.
Então,especificaremos o nosso modelo da seguinte maneira, Mass\_lost em
função de Airtemp,Cloud e Shade. E indicamos que as variáveis está dento
do conjunto de dados chamada dados.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nhst}\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Mass\_lost}\SpecialCharTok{\textasciitilde{}}\NormalTok{Airtemp}\SpecialCharTok{+}\NormalTok{Cloud}\SpecialCharTok{+}\NormalTok{Shade, }\AttributeTok{data =}\NormalTok{ dados)}
\NormalTok{nhst}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Mass_lost ~ Airtemp + Cloud + Shade, data = dados)
## 
## Coefficients:
## (Intercept)      Airtemp        Cloud       Shade1  
##    2.420982    -0.005843    -0.006114    -0.789149
\end{verbatim}

Pronto, o modelo já foi ajustado, podemos ler o ajuste do modelo da
seguinte forma:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Intercep= média da Mass\_loss para os indivíduos que não está na
  sombra.
\item
  Airtemp= é o tamanho de efeito(a1) da Airtemp sobre a Mass\_loss (aqui
  o tamanho de efeito é representado pelo coeficiente de inclinação da
  reta).
\item
  Clound= é o tamanho de efeito(a1) da Cloud sobre a Mass\_loss.
\item
  Shade1= é o tamanho de efeito da variável Shade sobre o Mass\_loss, ou
  seja, é a diferença entre as médias de Mass\_loss no tratamento 1 e 0.
\end{enumerate}

Podemos obter o valor da média de Mass\_loss no tratamento shade1
subtraindo do intercept o valor do tamanho de efeito.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coefi}\OtherTok{\textless{}{-}}\NormalTok{ nhst}\SpecialCharTok{$}\NormalTok{coefficients}
\NormalTok{coefi[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{{-}}\FunctionTok{abs}\NormalTok{(coefi[}\DecValTok{4}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept) 
##    1.631833
\end{verbatim}

Podemos observar então que o valor da média de Mass\_loss em Shade1 que
são aqueles indivíduos coletados em ambiente sombreado é igual a
1.631833

1.2. Agora vamos verificar o valor de p para saber se iremos rejeitar a
hipótese nula.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(nhst)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Mass_lost ~ Airtemp + Cloud + Shade, data = dados)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.2807 -1.0398 -0.5520  0.7802  6.1824 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)  
## (Intercept)  2.420982   1.020847   2.372   0.0193 *
## Airtemp     -0.005843   0.035398  -0.165   0.8692  
## Cloud       -0.006114   0.005177  -1.181   0.2401  
## Shade1      -0.789149   0.328119  -2.405   0.0177 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.596 on 117 degrees of freedom
## Multiple R-squared:  0.07631,    Adjusted R-squared:  0.05263 
## F-statistic: 3.222 on 3 and 117 DF,  p-value: 0.02524
\end{verbatim}

Nesse caso então, rejeitamos a hipótese nula e aceitamos a hipótese
alternativa, e de acordo com os nossas resultados, há diferença na perda
de massa corporal entre indivíduos que estão na sombra e indivíduos que
não estão na sombra. Sendo que indivíduos que não estão na sombra perdem
0.789 gramas a mais que os indivídos que estão na sombra.

\hypertarget{intervalo-de-confianuxe7a}{%
\subsection{Intervalo de confiança}\label{intervalo-de-confianuxe7a}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{intconf}\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Mass\_lost}\SpecialCharTok{\textasciitilde{}}\NormalTok{Airtemp}\SpecialCharTok{+}\NormalTok{Cloud}\SpecialCharTok{+}\NormalTok{Shade, }\AttributeTok{data =}\NormalTok{ dados)}
\FunctionTok{confint.lm}\NormalTok{(}\AttributeTok{object =}\NormalTok{ intconf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  2.5 %       97.5 %
## (Intercept)  0.3992479  4.442716366
## Airtemp     -0.0759474  0.064260803
## Cloud       -0.0163671  0.004139941
## Shade1      -1.4389721 -0.139325345
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(intconf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  (Intercept)      Airtemp        Cloud       Shade1 
##  2.420982139 -0.005843298 -0.006113580 -0.789148745
\end{verbatim}

Selecao de modelos

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{comp}\OtherTok{\textless{}{-}}\FunctionTok{lm}\NormalTok{(Mass\_lost}\SpecialCharTok{\textasciitilde{}}\NormalTok{Airtemp}\SpecialCharTok{+}\NormalTok{Cloud}\SpecialCharTok{+}\NormalTok{Shade, }\AttributeTok{data =}\NormalTok{ dados)}
\NormalTok{tempcl}\OtherTok{\textless{}{-}}\FunctionTok{lm}\NormalTok{(Mass\_lost}\SpecialCharTok{\textasciitilde{}}\NormalTok{Airtemp}\SpecialCharTok{+}\NormalTok{Cloud, }\AttributeTok{data =}\NormalTok{ dados)}
\NormalTok{tempsh}\OtherTok{\textless{}{-}}\FunctionTok{lm}\NormalTok{(Mass\_lost}\SpecialCharTok{\textasciitilde{}}\NormalTok{Airtemp}\SpecialCharTok{+}\NormalTok{Shade, }\AttributeTok{data =}\NormalTok{ dados)}

\NormalTok{contraste}\OtherTok{\textless{}{-}} \FunctionTok{model.sel}\NormalTok{(comp,tempcl, tempsh)}
\NormalTok{contraste}\OtherTok{\textless{}{-}}\NormalTok{contraste[,}\FunctionTok{c}\NormalTok{(}\DecValTok{6}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in `[.model.selection`(contraste, , c(6:10)): cannot recalculate
## "weights" on an incomplete object
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{contraste}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        df    logLik     AICc     delta     weight
## tempsh  4 -226.9641 462.2731 0.0000000 0.55553752
## comp    5 -226.2474 463.0165 0.7434163 0.38307393
## tempcl  4 -229.1668 466.6785 4.4054254 0.06138856
\end{verbatim}

\end{document}
